import React from 'react';

const AnalysisResultModal = ({ media, onClose }) => {
  if (!media) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 p-4">
      <div className="bg-gray-800 rounded-lg max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-start mb-4">
            <h2 className="text-xl font-bold">Analysis Complete</h2>
            <button 
              onClick={onClose}
              className="text-gray-400 hover:text-white"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          <div className="flex flex-col md:flex-row gap-6">
            <div className="md:w-1/2">
              {media.type === 'image' ? (
                <img 
                  src={media.fileUrl} 
                  alt="Media" 
                  className="w-full rounded-lg"
                />
              ) : (
                <video 
                  src={media.fileUrl} 
                  className="w-full rounded-lg" 
                  controls
                ></video>
              )}
            </div>

            <div className="md:w-1/2 space-y-4">
              <div>
                <h3 className="text-lg font-semibold mb-2">Analysis Result</h3>
                <div className={`inline-block px-3 py-1 rounded text-sm font-medium ${media.isAIGenerated ? 'bg-red-600' : 'bg-green-600'}`}>
                  {media.isAIGenerated ? 'AI Generated' : 'Real Media'}
                </div>
              </div>

              {media.tags && media.tags.length > 0 && (
                <div>
                  <h3 className="text-lg font-semibold mb-2">Detected Tags</h3>
                  <div className="flex flex-wrap gap-2">
                    {media.tags.map((tag, index) => (
                      <span key={index} className="bg-gray-700 px-2 py-1 rounded text-sm">
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              <div className="bg-gray-700 p-4 rounded-lg">
                <h3 className="text-lg font-semibold mb-2">What This Means</h3>
                {media.isAIGenerated ? (
                  <p>
                    Our analysis indicates this media was likely generated by AI. 
                    AI-generated content often has specific patterns and characteristics 
                    that our detection system can identify.
                  </p>
                ) : (
                  <p>
                    Our analysis indicates this media is likely authentic and not 
                    generated by AI. The natural patterns and characteristics of this 
                    content match those typically found in real media.
                  </p>
                )}
              </div>
            </div>
          </div>

          <div className="mt-6 text-center">
            <button
              onClick={onClose}
              className="px-6 py-2 bg-blue-600 hover:bg-blue-700 rounded-md transition text-lg font-medium"
            >
              OK
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AnalysisResultModal;